### ISSUE TITLE
[Feature Request] - Icons support

### ISSUE THREAD

**Issue by edersong** [billettg/npmhome#7]
It would be great if supports icons.
You can use https://github.com/walkxcode/dashboard-icons as baseline.

**Comment by billettg** [comment]
I totally agree, I tried implementing this by extracting the favicon from the HTML and path, but it was unreliable so scrapped it at the last minute. I plan to revisit this and use a more reliable method, thanks for the suggestion, looks very promising.

**Comment by billettg** [comment]
Implemented :)
