### ISSUE TITLE
Issue running through reverse proxy

### ISSUE THREAD

**Issue by vvstubbs** [billettg/npmhome#8]
Everthing seems to be working except if npmhome, located on an intel server pointing to nginx proxy manager on the PI4 through the proxies  externally mapped npmhome.example.com.then it reports it can not find the npm instance ip address. now if the npmhome was running on the same host as npm I would presume this would be a none issue as it would be able to find local host

**Comment by billettg** [comment]
How have you deployed npmhome, Docker or running the http-server?

I run npmhome on an Ubuntu server in Docker and I can access it fine via my reverse proxy using a proxy host mapping in NPM to the IP of the server and port 1234 using http.

I have *.lan mapped on my DNS server to point to NPM host, and then http://home.lan forwards this communication onwards.

Perhaps there is a DNS issue, or misconfigured NPM proxy host?

Is npmhome running and listening on the desired port (1234 by default)?

Are there any firewalls blocking the communication?

What do the http-server logs show?

**Comment by billettg** [comment]
If you're running it through Docker desktop, make sure when you run the container, go to optional settings > ports, and set the host port to your desired port (doesn't have to be 1234). You can then access it via localhost:port. If you don't specify a host port, Docker will pick a random one for you.

**Comment by vvstubbs** [comment]
not quite, I have the docker compose ports: 1234:1234 but yes the first set could be anything. I'm referring to setting up a external facing host name through nginx proxy manager, to say home.example.com, with basic auth, so the dashsboard could be accessed externally.

**Comment by esetgareth** [comment]
When you say externally do you mean public facing or external as in on your LAN but not localhost? The http-server should bind to 0.0.0.0 (all IP addresses), so if the configuration is correct and ports are mapped to 1234:1234 and NPM is set to forward sub.example.com to your IP:1234 then it should work:

```
Available on:
  http://127.0.0.1:1234
  http://192.168.0.254:1234
  http://100.109.4.36:1234
  http://172.21.0.1:1234
Hit CTRL-C to stop the server
```

**Comment by esetgareth** [comment]
I just tested it with basic auth as well, and it works fine again. It really is a very simple http-server and should work the same as any other docker container.

**Comment by vvstubbs** [comment]
It's okay, I just tried it again, I must have been me, sorry
